/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    ClipBoard: typeof import('./src/components/ClipBoard/index.vue')['default']
    IconFont: typeof import('./src/components/IconFont/index.vue')['default']
    IconFontQatypeIcon: typeof import('./src/components/IconFont/QatypeIcon.vue')['default']
    IconifyIcon: typeof import('./src/components/IconifyIcon/index.vue')['default']
    LayoutDefault: typeof import('./src/components/Layout/default.vue')['default']
    LayoutSidearPage: typeof import('./src/components/Layout/SidearPage.vue')['default']
    LayoutSlotArea: typeof import('./src/components/Layout/SlotArea.vue')['default']
    LayoutSlotCenterPanel: typeof import('./src/components/Layout/SlotCenterPanel.vue')['default']
    LayoutSlotFrame: typeof import('./src/components/Layout/SlotFrame.vue')['default']
    MarkdownPreview: typeof import('./src/components/MarkdownPreview/index.vue')['default']
    MarkdownPreviewMarkdownEcharts: typeof import('./src/components/MarkdownPreview/MarkdownEcharts.vue')['default']
    MarkdownPreviewMarkdownTable: typeof import('./src/components/MarkdownPreview/MarkdownTable.vue')['default']
    NavigationNavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
    NavigationNavFooter: typeof import('./src/components/Navigation/NavFooter.vue')['default']
    NavigationNavOctocat: typeof import('./src/components/Navigation/NavOctocat.vue')['default']
    NavigationNavSideBar: typeof import('./src/components/Navigation/NavSideBar.vue')['default']
    NavigationSideBar: typeof import('./src/components/Navigation/SideBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSplit: typeof import('naive-ui')['NSplit']
    NTag: typeof import('naive-ui')['NTag']
    NUpload: typeof import('naive-ui')['NUpload']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarItem: typeof import('./src/components/SideBar/Item.vue')['default']
    TableList: typeof import('./src/components/TableList/index.vue')['default']
  }
}
