/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {***REMOVED***

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue'***REMOVED***['default']
    ClipBoard: typeof import('./src/components/ClipBoard/index.vue'***REMOVED***['default']
    IconFont: typeof import('./src/components/IconFont/index.vue'***REMOVED***['default']
    IconFontQatypeIcon: typeof import('./src/components/IconFont/QatypeIcon.vue'***REMOVED***['default']
    IconifyIcon: typeof import('./src/components/IconifyIcon/index.vue'***REMOVED***['default']
    LayoutDefault: typeof import('./src/components/Layout/default.vue'***REMOVED***['default']
    LayoutSidearPage: typeof import('./src/components/Layout/SidearPage.vue'***REMOVED***['default']
    LayoutSlotArea: typeof import('./src/components/Layout/SlotArea.vue'***REMOVED***['default']
    LayoutSlotCenterPanel: typeof import('./src/components/Layout/SlotCenterPanel.vue'***REMOVED***['default']
    LayoutSlotFrame: typeof import('./src/components/Layout/SlotFrame.vue'***REMOVED***['default']
    MarkdownPreview: typeof import('./src/components/MarkdownPreview/index.vue'***REMOVED***['default']
    MarkdownPreviewMarkdownEcharts: typeof import('./src/components/MarkdownPreview/MarkdownEcharts.vue'***REMOVED***['default']
    MarkdownPreviewMarkdownTable: typeof import('./src/components/MarkdownPreview/MarkdownTable.vue'***REMOVED***['default']
    NavigationNavBar: typeof import('./src/components/Navigation/NavBar.vue'***REMOVED***['default']
    NavigationNavFooter: typeof import('./src/components/Navigation/NavFooter.vue'***REMOVED***['default']
    NavigationNavOctocat: typeof import('./src/components/Navigation/NavOctocat.vue'***REMOVED***['default']
    NavigationNavSideBar: typeof import('./src/components/Navigation/NavSideBar.vue'***REMOVED***['default']
    NavigationSideBar: typeof import('./src/components/Navigation/SideBar.vue'***REMOVED***['default']
    NButton: typeof import('naive-ui'***REMOVED***['NButton']
    NCard: typeof import('naive-ui'***REMOVED***['NCard']
    NConfigProvider: typeof import('naive-ui'***REMOVED***['NConfigProvider']
    NDataTable: typeof import('naive-ui'***REMOVED***['NDataTable']
    NDialogProvider: typeof import('naive-ui'***REMOVED***['NDialogProvider']
    NDivider: typeof import('naive-ui'***REMOVED***['NDivider']
    NDropdown: typeof import('naive-ui'***REMOVED***['NDropdown']
    NFloatButton: typeof import('naive-ui'***REMOVED***['NFloatButton']
    NForm: typeof import('naive-ui'***REMOVED***['NForm']
    NFormItem: typeof import('naive-ui'***REMOVED***['NFormItem']
    NIcon: typeof import('naive-ui'***REMOVED***['NIcon']
    NInput: typeof import('naive-ui'***REMOVED***['NInput']
    NLayout: typeof import('naive-ui'***REMOVED***['NLayout']
    NLayoutContent: typeof import('naive-ui'***REMOVED***['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui'***REMOVED***['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui'***REMOVED***['NLayoutHeader']
    NLoadingBarProvider: typeof import('naive-ui'***REMOVED***['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui'***REMOVED***['NMessageProvider']
    NModal: typeof import('naive-ui'***REMOVED***['NModal']
    NNotificationProvider: typeof import('naive-ui'***REMOVED***['NNotificationProvider']
    NPagination: typeof import('naive-ui'***REMOVED***['NPagination']
    NPopover: typeof import('naive-ui'***REMOVED***['NPopover']
    NProgress: typeof import('naive-ui'***REMOVED***['NProgress']
    NResult: typeof import('naive-ui'***REMOVED***['NResult']
    NSpace: typeof import('naive-ui'***REMOVED***['NSpace']
    NSpin: typeof import('naive-ui'***REMOVED***['NSpin']
    NSplit: typeof import('naive-ui'***REMOVED***['NSplit']
    NTag: typeof import('naive-ui'***REMOVED***['NTag']
    NUpload: typeof import('naive-ui'***REMOVED***['NUpload']
    Pagination: typeof import('./src/components/Pagination/index.vue'***REMOVED***['default']
    RouterLink: typeof import('vue-router'***REMOVED***['RouterLink']
    RouterView: typeof import('vue-router'***REMOVED***['RouterView']
    SideBarItem: typeof import('./src/components/SideBar/Item.vue'***REMOVED***['default']
    TableList: typeof import('./src/components/TableList/index.vue'***REMOVED***['default']
  ***REMOVED***
***REMOVED***
